name = "Hex"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff17c1a17f4b371494d4f80736e20ffe9f9b0e3ec7f6cf07caea4567ca534ac6"

[versions]
fabric = "0.16.14"
lwjgl3 = "3.3.1"
minecraft = "1.19.2"
unsup = "1.1.3"
