name = "Hex"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3250801867b45dca393be21d7ae26f6bfad55b3818ed93f7142f772cd8e6ff6e"

[versions]
fabric = "0.16.14"
lwjgl3 = "3.3.1"
minecraft = "1.19.2"
unsup = "1.1.3"
