name = "Hex"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbaeff3bea820e2f2c6719cb9c982c69291ba9ceda8a424e2b05a80d0a19bc27"

[versions]
fabric = "0.16.14"
lwjgl3 = "3.3.1"
minecraft = "1.19.2"
unsup = "1.1.3"
