name = "Hex"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba72754c78bef2b4bdd782aa800a3b2f463c676a9bcfd27ace61ef5f45ee0716"

[versions]
fabric = "0.16.14"
lwjgl3 = "3.3.1"
minecraft = "1.19.2"
unsup = "1.1.3"
