name = "Hex"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00a99d1a58fcaa1f701e02c7afa2f4408036f764a3f9510d9e581b2428a1db3"

[versions]
fabric = "0.16.14"
lwjgl3 = "3.3.1"
minecraft = "1.19.2"
unsup = "1.1.3"
