# Flavor groups
[flavor_groups.low_power]
name = "Low power mode"
description = "Disables any mods that only add eyecandy and could hurt performance.\nDoes not disable anything meant to boost performance or that adds functionality."
side = "client"
choices = ["low_power_off", "low_power_on"]

[flavor_groups.gui_changes]
name = "Gui changes"
description = "Eyecandy that I personally like (crosshair changes mostly)"
side = "client"
choices = ["gui_changes_off", "gui_changes_on"]

[flavor_groups.map_mod]
name = "Map mod to use"
description = "Pick your prefered map mod"
side = "client"

[[flavor_groups.map_mod.choices]]
id = "map_mod_ftb"
name = "FTB Chunks"
description = "Leaves FTB Chunks fallback map as the mapping mod"

[[flavor_groups.map_mod.choices]]
id = "map_mod_journeymap"
name = "JourneyMap"
description = "Installs JourneyMap which integrates with FTB Chunks"

# Apply the flavors
[metafile.distanthorizons]
flavors = "low_power_off"
[metafile.dynamiccrosshair]
flavors = "gui_changes_on"
[metafile.flightassistant]
flavors = "gui_changes_on"
[metafile.armorpoints]
flavors = "gui_changes_on"
[metafile.journeymap]
flavors = "map_mod_journeymap"
