{
  "endMobs": [
    "minecraft:enderman",
    "minecraft:endermite",
    "minecraft:ender_dragon",
    "minecraft:shulker"
  ],
  "gristleTeleport": true,
  "teleportRangeSize": 24,
  "teleportMaxHeight": 32
}